# Generated by Django 6.0.6 on 2026-06-27 23:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("origami_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord",
            field=models.CharField(
                blank=True,
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid Discord username (2-32 alphanumeric, underscores, periods)",
                        regex="^[a-zA-Z0-9_.]{2,32}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_dm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_player",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_role_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number (7-20 digits, may include +, spaces, dashes)",
                        regex="^\\+?[\\d\\s\\-]{7,20}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_contact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("discord", "Discord"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="real_name",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
